#Each new term in the Fibonacci sequence is generated by adding the 
#previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not 
#exceed four million, find the sum of the even-valued terms.
Fnum = [1,2]
i = 0
sum = 2
while Fnum[i] + Fnum[i+1] <= 4000000:
    Fnum.append( Fnum[i] + Fnum[i+1] )
    if ( Fnum[i] + Fnum[i+1] ) % 2 == 0:
        sum += Fnum[i] + Fnum[i+1]
    i += 1
print(sum)
